"""C++ loop-nest emitter for CC residual equations.

Supports:
- Naive (unoptimized) loop nests
- Loop tiling for cache locality
- OpenMP parallelization
- Intermediate tensor emission
- BLAS/GEMM lowering (Phase 3)
- Memory layout annotations (Phase 3)

Use ``emit_translation_unit`` for naive output or
``emit_optimized_translation_unit`` for tiled + OpenMP output.
"""

from __future__ import annotations

from fractions import Fraction
from typing import Sequence, TYPE_CHECKING

from ..project import AlgebraTerm, manifold_rank
from ..tensors import Tensor
from ..indices import Index

if TYPE_CHECKING:
    from ..optimization.intermediates import IntermediateSpec
    from ..tensor_ir import BackendTermEx, BLASHint

# Default tile sizes (tuned for L1 cache ~32KB of doubles)
DEFAULT_TILE_OCC = 16
DEFAULT_TILE_VIR = 16


def _residual_name(target: str) -> str:
    """Map a manifold target name to a residual symbol."""
    if target == "energy":
        return "E_CC"
    try:
        rank = manifold_rank(target)
    except ValueError:
        return target
    return f"R{rank}"


def _loop_bound(idx: Index) -> str:
    if idx.space == "occ":
        return "no"
    if idx.space == "vir":
        return "nv"
    return "n"


def _tensor_access(t: Tensor) -> str:
    if t.name == "D":
        # Orbital energy denominator: (ε_a + ε_b + ... - ε_i - ε_j - ...)
        parts: list[str] = []
        for idx in t.indices:
            if idx.space == "vir":
                parts.append(f"+ eps({idx.name})")
            else:
                parts.append(f"- eps({idx.name})")
        expr = " ".join(parts)
        if expr.startswith("+ "):
            expr = expr[2:]
        return f"({expr})"

    idx_str = ", ".join(i.name for i in t.indices)
    name = t.name.upper()
    return f"{name}({idx_str})"


def _coeff_literal(c: Fraction) -> str:
    f = float(c)
    if f == int(f):
        v = int(f)
        if v == 1:
            return ""
        if v == -1:
            return "-"
        return f"{v} * "
    return f"{f} * "


def emit_term(
    term: AlgebraTerm,
    lhs: str = "R",
    indent: int = 0,
) -> str:
    """Emit a single term as a C++ loop nest with accumulator."""
    pad = " " * indent
    lines: list[str] = []

    free = list(term.free_indices)
    summed = list(term.summed_indices)
    has_summed = len(summed) > 0

    for idx in free:
        bound = _loop_bound(idx)
        lines.append(
            f"{pad}for (int {idx.name} = 0;"
            f" {idx.name} < {bound}; ++{idx.name})"
        )

    if has_summed:
        lines.append(f"{pad}{{")
        lines.append(f"{pad}    double acc = 0.0;")

        for idx in summed:
            bound = _loop_bound(idx)
            lines.append(
                f"{pad}    for (int {idx.name} = 0;"
                f" {idx.name} < {bound}; ++{idx.name})"
            )

        coeff = _coeff_literal(term.coeff)
        product = " * ".join(_tensor_access(f) for f in term.factors)
        lines.append(f"{pad}        acc += {coeff}{product};")

        free_str = ", ".join(i.name for i in free)
        lines.append(f"{pad}    {lhs}({free_str}) += acc;")
        lines.append(f"{pad}}}")
    else:
        lines.append(f"{pad}{{")
        coeff = _coeff_literal(term.coeff)
        product = " * ".join(_tensor_access(f) for f in term.factors)
        free_str = ", ".join(i.name for i in free)
        if product:
            lines.append(f"{pad}    {lhs}({free_str}) += {coeff}{product};")
        else:
            lines.append(f"{pad}    {lhs}({free_str}) += {coeff};")
        lines.append(f"{pad}}}")

    return "\n".join(lines)


def emit_residual(
    name: str,
    terms: Sequence[AlgebraTerm],
    free_indices: tuple[Index, ...] | None = None,
) -> str:
    """Emit a full residual function as C++ code."""
    if free_indices is None and terms:
        free_indices = terms[0].free_indices

    lines: list[str] = []
    lines.append(f"// {name} residual ({len(terms)} terms)")
    free_str = ', '.join(i.name for i in (free_indices or ()))
    lines.append(f"// Free indices: {free_str}")
    lines.append("")

    for i, t in enumerate(terms):
        lines.append(f"// Term {i + 1}")
        lines.append(emit_term(t, lhs=name))
        lines.append("")

    return "\n".join(lines)


def emit_translation_unit(
    equations: dict[str, list[AlgebraTerm]],
    function_name: str = "compute_cc_residuals",
) -> str:
    """Emit a complete C++ source file with all residuals."""
    lines: list[str] = []
    lines.append("// Auto-generated by ccgen")
    lines.append("// Spin-orbital coupled-cluster residual equations")
    lines.append("")
    lines.append("#include <cstddef>")
    lines.append("")
    lines.append(f"void {function_name}(")
    lines.append("    const int no, const int nv,")

    # Build accessor comment from the actual equation targets.
    accessors = ["F", "V"]
    for target in equations:
        accessors.append(_residual_name(target))
    lines.append(
        f"    /* tensor accessors: {', '.join(accessors)} */"
    )
    lines.append(") {")
    lines.append("")

    for target, terms in equations.items():
        lhs = _residual_name(target)
        lines.append(emit_residual(lhs, terms))

    lines.append("}")
    return "\n".join(lines)


def emit_intermediate_build(
    spec: IntermediateSpec,
    indent: int = 4,
) -> str:
    """Emit C++ code to build a single intermediate tensor."""
    pad = " " * indent
    lines: list[str] = []

    lines.append(f"{pad}// Intermediate {spec.name} "
                 f"({spec.index_space_sig}, rank {spec.rank})")

    # Zero-initialize
    free = list(spec.indices)
    if free:
        dims = " * ".join(_loop_bound(idx) for idx in free)
        lines.append(f"{pad}// Shape: {dims}")

    for defn_term in spec.definition_terms:
        lines.append(emit_term(defn_term, lhs=spec.name, indent=indent))

    lines.append("")
    return "\n".join(lines)


def emit_intermediate_builds(
    intermediates: Sequence[IntermediateSpec],
    indent: int = 4,
) -> str:
    """Emit C++ code for all intermediate tensor builds."""
    if not intermediates:
        return ""

    lines: list[str] = []
    pad = " " * indent
    lines.append(f"{pad}// ── Intermediate tensor builds "
                 f"({len(intermediates)} intermediates) ──")
    lines.append("")

    for spec in intermediates:
        lines.append(emit_intermediate_build(spec, indent=indent))

    return "\n".join(lines)


def emit_translation_unit_with_intermediates(
    equations: dict[str, list[AlgebraTerm]],
    intermediates: Sequence[IntermediateSpec] | None = None,
    function_name: str = "compute_cc_residuals",
) -> str:
    """Emit a complete C++ source file with intermediate builds + residuals."""
    lines: list[str] = []
    lines.append("// Auto-generated by ccgen")
    lines.append("// Spin-orbital coupled-cluster residual equations")
    if intermediates:
        lines.append(f"// With {len(intermediates)} intermediate tensors")
    lines.append("")
    lines.append("#include <cstddef>")
    lines.append("")
    lines.append(f"void {function_name}(")
    lines.append("    const int no, const int nv,")

    accessors = ["F", "V"]
    for target in equations:
        accessors.append(_residual_name(target))
    if intermediates:
        for spec in intermediates:
            accessors.append(spec.name)
    lines.append(
        f"    /* tensor accessors: {', '.join(accessors)} */"
    )
    lines.append(") {")
    lines.append("")

    if intermediates:
        lines.append(emit_intermediate_builds(intermediates))
        lines.append("")

    for target, terms in equations.items():
        lhs = _residual_name(target)
        lines.append(emit_residual(lhs, terms))

    lines.append("}")
    return "\n".join(lines)


# ── Optimized emitters: loop tiling + OpenMP ────────────────────────


def _tile_var(idx: Index) -> str:
    """Tile block variable name for an index."""
    return f"{idx.name}b"


def _tile_size(idx: Index, tile_occ: int, tile_vir: int) -> str:
    if idx.space == "occ":
        return str(tile_occ)
    if idx.space == "vir":
        return str(tile_vir)
    return str(min(tile_occ, tile_vir))


def emit_term_tiled(
    term: AlgebraTerm,
    lhs: str = "R",
    indent: int = 0,
    tile_occ: int = DEFAULT_TILE_OCC,
    tile_vir: int = DEFAULT_TILE_VIR,
    use_openmp: bool = True,
    omp_collapse: int | None = None,
) -> str:
    """Emit a single term as a tiled C++ loop nest with OpenMP.

    Free indices are tiled; summed (contraction) indices are not
    tiled since they iterate over accumulation dimensions.

    Parameters
    ----------
    tile_occ, tile_vir : int
        Tile sizes for occupied and virtual index dimensions.
    use_openmp : bool
        If True, emit ``#pragma omp parallel for`` on outer tile loops.
    omp_collapse : int or None
        Number of outer tile loops to collapse.  If None, collapses
        all free-index tile loops (up to 4).
    """
    pad = " " * indent
    lines: list[str] = []

    free = list(term.free_indices)
    summed = list(term.summed_indices)
    has_summed = len(summed) > 0

    # If only 0 or 1 free indices, tiling has no benefit
    if len(free) <= 1:
        return emit_term(term, lhs=lhs, indent=indent)

    n_collapse = omp_collapse if omp_collapse is not None else min(len(free), 4)

    # Outer tile loops over free indices
    if use_openmp and n_collapse > 0:
        lines.append(
            f"{pad}#pragma omp parallel for collapse({n_collapse})"
            f" schedule(dynamic)"
        )
    for idx in free:
        bound = _loop_bound(idx)
        ts = _tile_size(idx, tile_occ, tile_vir)
        bv = _tile_var(idx)
        lines.append(
            f"{pad}for (int {bv} = 0; {bv} < {bound}; {bv} += {ts})"
        )

    # Inner point loops within each tile
    for idx in free:
        bound = _loop_bound(idx)
        ts = _tile_size(idx, tile_occ, tile_vir)
        bv = _tile_var(idx)
        lines.append(
            f"{pad}for (int {idx.name} = {bv};"
            f" {idx.name} < std::min({bv} + {ts}, {bound});"
            f" ++{idx.name})"
        )

    if has_summed:
        lines.append(f"{pad}{{")
        lines.append(f"{pad}    double acc = 0.0;")

        for idx in summed:
            bound = _loop_bound(idx)
            lines.append(
                f"{pad}    for (int {idx.name} = 0;"
                f" {idx.name} < {bound}; ++{idx.name})"
            )

        coeff = _coeff_literal(term.coeff)
        product = " * ".join(_tensor_access(f) for f in term.factors)
        lines.append(f"{pad}        acc += {coeff}{product};")

        free_str = ", ".join(i.name for i in free)
        lines.append(f"{pad}    {lhs}({free_str}) += acc;")
        lines.append(f"{pad}}}")
    else:
        lines.append(f"{pad}{{")
        coeff = _coeff_literal(term.coeff)
        product = " * ".join(_tensor_access(f) for f in term.factors)
        free_str = ", ".join(i.name for i in free)
        if product:
            lines.append(f"{pad}    {lhs}({free_str}) += {coeff}{product};")
        else:
            lines.append(f"{pad}    {lhs}({free_str}) += {coeff};")
        lines.append(f"{pad}}}")

    return "\n".join(lines)


def emit_residual_optimized(
    name: str,
    terms: Sequence[AlgebraTerm],
    free_indices: tuple[Index, ...] | None = None,
    tile_occ: int = DEFAULT_TILE_OCC,
    tile_vir: int = DEFAULT_TILE_VIR,
    use_openmp: bool = True,
) -> str:
    """Emit a full residual with tiled + OpenMP loop nests."""
    if free_indices is None and terms:
        free_indices = terms[0].free_indices

    lines: list[str] = []
    lines.append(f"// {name} residual ({len(terms)} terms)")
    free_str = ', '.join(i.name for i in (free_indices or ()))
    lines.append(f"// Free indices: {free_str}")
    if free_indices and len(free_indices) > 1:
        lines.append(
            f"// Tile sizes: occ={tile_occ}, vir={tile_vir}"
        )
    lines.append("")

    for i, t in enumerate(terms):
        lines.append(f"// Term {i + 1}")
        lines.append(emit_term_tiled(
            t, lhs=name,
            tile_occ=tile_occ, tile_vir=tile_vir,
            use_openmp=use_openmp,
        ))
        lines.append("")

    return "\n".join(lines)


def emit_optimized_translation_unit(
    equations: dict[str, list[AlgebraTerm]],
    intermediates: Sequence[IntermediateSpec] | None = None,
    function_name: str = "compute_cc_residuals",
    tile_occ: int = DEFAULT_TILE_OCC,
    tile_vir: int = DEFAULT_TILE_VIR,
    use_openmp: bool = True,
) -> str:
    """Emit a C++ source file with tiled loops and OpenMP parallelization.

    Parameters
    ----------
    tile_occ, tile_vir : int
        Tile sizes for occupied and virtual index dimensions.
    use_openmp : bool
        If True, emit OpenMP pragmas on outer tile loops.
    """
    lines: list[str] = []
    lines.append("// Auto-generated by ccgen (optimized)")
    lines.append("// Spin-orbital coupled-cluster residual equations")
    lines.append(f"// Loop tiling: occ={tile_occ}, vir={tile_vir}")
    if use_openmp:
        lines.append("// OpenMP parallelization enabled")
    if intermediates:
        lines.append(f"// With {len(intermediates)} intermediate tensors")
    lines.append("")
    lines.append("#include <cstddef>")
    lines.append("#include <algorithm>")
    if use_openmp:
        lines.append("#include <omp.h>")
    lines.append("")
    lines.append(f"void {function_name}(")
    lines.append("    const int no, const int nv,")

    accessors = ["F", "V"]
    for target in equations:
        accessors.append(_residual_name(target))
    if intermediates:
        for spec in intermediates:
            accessors.append(spec.name)
    lines.append(
        f"    /* tensor accessors: {', '.join(accessors)} */"
    )
    lines.append(") {")
    lines.append("")

    if intermediates:
        lines.append(emit_intermediate_builds(intermediates))
        lines.append("")

    for target, terms in equations.items():
        lhs = _residual_name(target)
        lines.append(emit_residual_optimized(
            lhs, terms,
            tile_occ=tile_occ, tile_vir=tile_vir,
            use_openmp=use_openmp,
        ))

    lines.append("}")
    return "\n".join(lines)


# ── Phase 3: BLAS/GEMM lowering ───────────────────────────────────


def emit_gemm_call(
    hint: BLASHint,
    lhs: str,
    lhs_indices: tuple[Index, ...],
    coefficient: Fraction,
    indent: int = 4,
) -> str:
    """Emit a CBLAS dgemm call for a recognized GEMM pattern.

    Generates code like::

        cblas_dgemm(CblasRowMajor, CblasNoTrans, CblasNoTrans,
                    m, n, k, alpha,
                    A_data, lda, B_data, ldb,
                    1.0, C_data, ldc);

    Parameters
    ----------
    hint : BLASHint
        The recognized BLAS pattern from tensor IR analysis.
    lhs : str
        Name of the output tensor (residual).
    lhs_indices : tuple of Index
        Free indices of the output tensor.
    coefficient : Fraction
        Numerical coefficient (alpha in GEMM).
    indent : int
        Indentation level.
    """
    pad = " " * indent
    lines: list[str] = []

    # Translate pattern to CBLAS transpose flags
    trans_map = {
        "gemm_nn": ("CblasNoTrans", "CblasNoTrans"),
        "gemm_nt": ("CblasNoTrans", "CblasTrans"),
        "gemm_tn": ("CblasTrans", "CblasNoTrans"),
        "gemm_tt": ("CblasTrans", "CblasTrans"),
    }
    trans_a, trans_b = trans_map.get(hint.pattern, ("CblasNoTrans", "CblasNoTrans"))

    # Dimension variables
    m_dims = " * ".join(_loop_bound(idx) for idx in hint.m_indices) if hint.m_indices else "1"
    n_dims = " * ".join(_loop_bound(idx) for idx in hint.n_indices) if hint.n_indices else "1"
    k_dims = " * ".join(_loop_bound(idx) for idx in hint.contraction_indices)

    alpha = float(coefficient)
    a_name = hint.a_tensor.upper()
    b_name = hint.b_tensor.upper()

    lines.append(f"{pad}// BLAS GEMM: {lhs} += {alpha} * {a_name} * {b_name}")
    lines.append(f"{pad}// Pattern: {hint.pattern}")
    lines.append(f"{pad}// M={m_dims}, N={n_dims}, K={k_dims}")

    # Emit outer loops for any batch dimensions (indices in LHS
    # that are in neither m nor n of the GEMM)
    batch_indices = [
        idx for idx in lhs_indices
        if idx not in hint.m_indices and idx not in hint.n_indices
    ]

    for idx in batch_indices:
        bound = _loop_bound(idx)
        lines.append(
            f"{pad}for (int {idx.name} = 0;"
            f" {idx.name} < {bound}; ++{idx.name})"
        )

    lines.append(f"{pad}{{")
    lines.append(f"{pad}    cblas_dgemm(CblasRowMajor,")
    lines.append(f"{pad}        {trans_a}, {trans_b},")
    lines.append(f"{pad}        {m_dims}, {n_dims}, {k_dims},")
    lines.append(f"{pad}        {alpha},  // alpha")
    lines.append(f"{pad}        {a_name}.data(), {m_dims if trans_a == 'CblasNoTrans' else k_dims},")
    lines.append(f"{pad}        {b_name}.data(), {k_dims if trans_b == 'CblasNoTrans' else n_dims},")
    lines.append(f"{pad}        1.0,  // beta")
    lines.append(f"{pad}        {lhs}.data(), {n_dims});")
    lines.append(f"{pad}}}")

    return "\n".join(lines)


def emit_term_with_blas(
    term_ex: BackendTermEx,
    lhs: str = "R",
    indent: int = 0,
    tile_occ: int = DEFAULT_TILE_OCC,
    tile_vir: int = DEFAULT_TILE_VIR,
    use_openmp: bool = True,
) -> str:
    """Emit a term using BLAS if a GEMM pattern is detected, else tiled loops.

    Falls back to ``emit_term_tiled`` when no BLAS pattern is available.
    """
    if term_ex.blas_hint is not None:
        return emit_gemm_call(
            term_ex.blas_hint,
            lhs,
            term_ex.lhs_indices,
            term_ex.coefficient,
            indent=indent,
        )

    # Fall back to the AlgebraTerm-based tiled emitter
    algebra_term = AlgebraTerm(
        coeff=term_ex.coefficient,
        factors=term_ex.rhs_factors,
        free_indices=term_ex.free_indices,
        summed_indices=term_ex.summed_indices,
        connected=term_ex.connected,
    )
    return emit_term_tiled(
        algebra_term, lhs=lhs, indent=indent,
        tile_occ=tile_occ, tile_vir=tile_vir,
        use_openmp=use_openmp,
    )


def emit_blas_translation_unit(
    equations: dict[str, list[AlgebraTerm]],
    intermediates: Sequence[IntermediateSpec] | None = None,
    function_name: str = "compute_cc_residuals",
    tile_occ: int = DEFAULT_TILE_OCC,
    tile_vir: int = DEFAULT_TILE_VIR,
    use_openmp: bool = True,
    use_blas: bool = True,
) -> str:
    """Emit C++ with BLAS/GEMM lowering where applicable.

    Uses the extended IR to detect GEMM patterns and emit CBLAS calls
    instead of explicit loop nests.  Falls back to tiled loops for
    terms without recognized BLAS patterns.
    """
    from ..tensor_ir import lower_equations_ex

    lines: list[str] = []
    lines.append("// Auto-generated by ccgen (BLAS-optimized)")
    lines.append("// Spin-orbital coupled-cluster residual equations")
    lines.append(f"// Loop tiling: occ={tile_occ}, vir={tile_vir}")
    if use_openmp:
        lines.append("// OpenMP parallelization enabled")
    if use_blas:
        lines.append("// BLAS/GEMM lowering enabled")
    if intermediates:
        lines.append(f"// With {len(intermediates)} intermediate tensors")
    lines.append("")
    lines.append("#include <cstddef>")
    lines.append("#include <algorithm>")
    if use_openmp:
        lines.append("#include <omp.h>")
    if use_blas:
        lines.append("#include <cblas.h>")
    lines.append("")
    lines.append(f"void {function_name}(")
    lines.append("    const int no, const int nv,")

    accessors = ["F", "V"]
    for target in equations:
        accessors.append(_residual_name(target))
    if intermediates:
        for spec in intermediates:
            accessors.append(spec.name)
    lines.append(
        f"    /* tensor accessors: {', '.join(accessors)} */"
    )
    lines.append(") {")
    lines.append("")

    if intermediates:
        lines.append(emit_intermediate_builds(intermediates))
        lines.append("")

    # Lower to extended IR for BLAS detection
    ex_equations = lower_equations_ex(
        equations,
        detect_blas=use_blas,
        tile_occ=tile_occ,
        tile_vir=tile_vir,
    )

    blas_count = 0
    loop_count = 0

    for target, ex_terms in ex_equations.items():
        lhs = _residual_name(target)
        lines.append(f"// {lhs} residual ({len(ex_terms)} terms)")
        lines.append("")

        for i, tex in enumerate(ex_terms):
            if tex.blas_hint is not None:
                lines.append(f"// Term {i + 1} [BLAS GEMM]")
                blas_count += 1
            else:
                lines.append(f"// Term {i + 1}")
                loop_count += 1

            lines.append(emit_term_with_blas(
                tex, lhs=lhs,
                tile_occ=tile_occ, tile_vir=tile_vir,
                use_openmp=use_openmp,
            ))
            lines.append("")

    lines.append(f"// Summary: {blas_count} BLAS calls, {loop_count} loop nests")
    lines.append("}")
    return "\n".join(lines)
