"""Naive C++ loop-nest emitter for CC residual equations."""

from __future__ import annotations

from fractions import Fraction
from typing import Sequence

from ..project import AlgebraTerm, manifold_rank
from ..tensors import Tensor
from ..indices import Index


def _residual_name(target: str) -> str:
    """Map a manifold target name to a residual symbol."""
    if target == "energy":
        return "E_CC"
    try:
        rank = manifold_rank(target)
    except ValueError:
        return target
    return f"R{rank}"


def _loop_bound(idx: Index) -> str:
    if idx.space == "occ":
        return "no"
    if idx.space == "vir":
        return "nv"
    return "n"


def _tensor_access(t: Tensor) -> str:
    idx_str = ", ".join(i.name for i in t.indices)
    name = t.name.upper()
    return f"{name}({idx_str})"


def _coeff_literal(c: Fraction) -> str:
    f = float(c)
    if f == int(f):
        v = int(f)
        if v == 1:
            return ""
        if v == -1:
            return "-"
        return f"{v} * "
    return f"{f} * "


def emit_term(
    term: AlgebraTerm,
    lhs: str = "R",
    indent: int = 0,
) -> str:
    """Emit a single term as a C++ loop nest with accumulator."""
    pad = " " * indent
    lines: list[str] = []

    free = list(term.free_indices)
    summed = list(term.summed_indices)
    has_summed = len(summed) > 0

    for idx in free:
        bound = _loop_bound(idx)
        lines.append(
            f"{pad}for (int {idx.name} = 0;"
            f" {idx.name} < {bound}; ++{idx.name})"
        )

    if has_summed:
        lines.append(f"{pad}{{")
        lines.append(f"{pad}    double acc = 0.0;")

        for idx in summed:
            bound = _loop_bound(idx)
            lines.append(
                f"{pad}    for (int {idx.name} = 0;"
                f" {idx.name} < {bound}; ++{idx.name})"
            )

        coeff = _coeff_literal(term.coeff)
        product = " * ".join(_tensor_access(f) for f in term.factors)
        lines.append(f"{pad}        acc += {coeff}{product};")

        free_str = ", ".join(i.name for i in free)
        lines.append(f"{pad}    {lhs}({free_str}) += acc;")
        lines.append(f"{pad}}}")
    else:
        lines.append(f"{pad}{{")
        coeff = _coeff_literal(term.coeff)
        product = " * ".join(_tensor_access(f) for f in term.factors)
        free_str = ", ".join(i.name for i in free)
        if product:
            lines.append(f"{pad}    {lhs}({free_str}) += {coeff}{product};")
        else:
            lines.append(f"{pad}    {lhs}({free_str}) += {coeff};")
        lines.append(f"{pad}}}")

    return "\n".join(lines)


def emit_residual(
    name: str,
    terms: Sequence[AlgebraTerm],
    free_indices: tuple[Index, ...] | None = None,
) -> str:
    """Emit a full residual function as C++ code."""
    if free_indices is None and terms:
        free_indices = terms[0].free_indices

    lines: list[str] = []
    lines.append(f"// {name} residual ({len(terms)} terms)")
    free_str = ', '.join(i.name for i in (free_indices or ()))
    lines.append(f"// Free indices: {free_str}")
    lines.append("")

    for i, t in enumerate(terms):
        lines.append(f"// Term {i + 1}")
        lines.append(emit_term(t, lhs=name))
        lines.append("")

    return "\n".join(lines)


def emit_translation_unit(
    equations: dict[str, list[AlgebraTerm]],
    function_name: str = "compute_cc_residuals",
) -> str:
    """Emit a complete C++ source file with all residuals."""
    lines: list[str] = []
    lines.append("// Auto-generated by ccgen")
    lines.append("// Spin-orbital coupled-cluster residual equations")
    lines.append("")
    lines.append("#include <cstddef>")
    lines.append("")
    lines.append(f"void {function_name}(")
    lines.append("    const int no, const int nv,")

    # Build accessor comment from the actual equation targets.
    accessors = ["F", "V"]
    for target in equations:
        accessors.append(_residual_name(target))
    lines.append(
        f"    /* tensor accessors: {', '.join(accessors)} */"
    )
    lines.append(") {")
    lines.append("")

    for target, terms in equations.items():
        lhs = _residual_name(target)
        lines.append(emit_residual(lhs, terms))

    lines.append("}")
    return "\n".join(lines)
