"""Planck-specific RCCSD warm-start emitter.

This backend emits the spin-orbital RCCSD warm-start kernels in the same
intermediate structure that Planck's validated native implementation uses.
Unlike the generic equation emitters, this target is intentionally solver-
shaped: it generates the GCCSD-style ``tau/fae/fmi/fme/wmnij/wabef/wmbej``
pipeline that the tensor RCCSDT warm-start stage expects.
"""

from __future__ import annotations


def emit_planck_spinorbital_rccsd_warm_start() -> str:
    """Emit the validated Planck-style RCCSD warm-start kernels."""
    return """// Auto-generated by ccgen for tensor_backend.cpp

[[nodiscard]] double compute_generated_spin_orbital_rccsd_correlation_energy(
    const ProductionSpinOrbitalReference &reference,
    const ProductionSpinOrbitalBlocks &blocks,
    const RCCSDAmplitudes &amps)
{
    double energy = 0.0;
    for (int i = 0; i < reference.n_occ; ++i)
        for (int j = 0; j < reference.n_occ; ++j)
            for (int a = 0; a < reference.n_virt; ++a)
                for (int b = 0; b < reference.n_virt; ++b)
                {
                    const double gijab = blocks.oovv(i, j, a, b);
                    energy += 0.25 * gijab * amps.t2(i, j, a, b);
                    energy += 0.5 * gijab * amps.t1(i, a) * amps.t1(j, b);
                }
    return energy;
}

[[nodiscard]] RCCSDResiduals compute_generated_spin_orbital_rccsd_residuals(
    const ProductionSpinOrbitalReference &reference,
    const ProductionSpinOrbitalBlocks &blocks,
    const RCCSDAmplitudes &amps)
{
    const TauCache tau_cache = build_tau_cache(amps);
    const RCCSDIntermediates ints = build_intermediates(
        reference, blocks, amps, tau_cache);
    return build_residuals(reference, blocks, amps, tau_cache, ints);
}
"""
