#include "post_hf/casscf/orbital.h"

#include "integrals/os.h"
#include "post_hf/integrals.h"

#include <Eigen/Eigenvalues>

#include <algorithm>
#include <limits>

namespace
{

    using HartreeFock::Correlation::CASSCFInternal::contract_q_matrix;
    using HartreeFock::Correlation::CASSCFInternal::apply_response_diag_preconditioner;
    using HartreeFock::Correlation::CASSCFInternal::project_orthogonal;

} // namespace

namespace HartreeFock::Correlation::CASSCF
{

    ActiveIntegralCache build_active_integral_cache(
        const std::vector<double> &eri,
        const Eigen::MatrixXd &C,
        int n_core,
        int n_act,
        int nbasis)
    {
        ActiveIntegralCache cache;
        cache.nbasis = nbasis;
        cache.nact = n_act;
        if (n_act == 0)
            return cache;

        // Cache the AO->(p, u, v, w) transformed ERIs once per macroiteration so
        // repeated Q-matrix contractions do not pay the four-index transform again.
        const Eigen::MatrixXd C_act = C.middleCols(n_core, n_act);
        cache.puvw = HartreeFock::Correlation::transform_eri(eri, nbasis, C, C_act, C_act, C_act);
        cache.valid = true;
        return cache;
    }

    Eigen::MatrixXd compute_Q_matrix(
        const ActiveIntegralCache &cache,
        const std::vector<double> &Gamma)
    {
        if (!cache.valid)
            return Eigen::MatrixXd::Zero(cache.nbasis, cache.nact);
        // Q(p,t) is the orbital-response contraction of the active-space 2-RDM
        // with the cached mixed-basis two-electron integrals.
        return contract_q_matrix(cache.puvw, Gamma, cache.nbasis, cache.nact);
    }

    Eigen::MatrixXd build_inactive_fock_mo(
        const Eigen::MatrixXd &C,
        const Eigen::MatrixXd &H_core,
        const std::vector<double> &eri,
        int n_core,
        int nbasis)
    {
        // The inactive/core contribution is the closed-shell Fock matrix generated
        // by doubly occupied core orbitals, transformed back into the current MO basis.
        if (n_core == 0)
            return C.transpose() * H_core * C;
        const Eigen::MatrixXd D = 2.0 * C.leftCols(n_core) * C.leftCols(n_core).transpose();
        return C.transpose() * (H_core + HartreeFock::ObaraSaika::_compute_fock_rhf(eri, D, nbasis)) * C;
    }

    Eigen::MatrixXd build_active_fock_mo(
        const Eigen::MatrixXd &C,
        const Eigen::MatrixXd &gamma,
        const std::vector<double> &eri,
        int n_core,
        int n_act,
        int nbasis)
    {
        // Build the generalized Fock contribution generated by the active-space
        // 1-RDM so the orbital gradient can mix core, active, and virtual blocks.
        if (n_act == 0)
            return Eigen::MatrixXd::Zero(nbasis, nbasis);
        const Eigen::MatrixXd C_act = C.middleCols(n_core, n_act);
        const Eigen::MatrixXd D_act = C_act * gamma * C_act.transpose();
        return C.transpose() * HartreeFock::ObaraSaika::_compute_fock_rhf(eri, D_act, nbasis) * C;
    }

    double compute_core_energy(
        const Eigen::MatrixXd &h_mo,
        const Eigen::MatrixXd &F_I_mo,
        int n_core)
    {
        double e = 0.0;
        for (int i = 0; i < n_core; ++i)
            e += h_mo(i, i) + F_I_mo(i, i);
        return e;
    }

    Eigen::MatrixXd compute_orbital_gradient(
        const Eigen::MatrixXd &F_I_mo,
        const Eigen::MatrixXd &F_A_mo,
        const Eigen::MatrixXd &Q,
        const Eigen::MatrixXd &gamma,
        int n_core,
        int n_act,
        int n_virt,
        const std::vector<int> &mo_irreps,
        bool use_sym)
    {
        const int nb = n_core + n_act + n_virt;
        const Eigen::MatrixXd F_sum = F_I_mo + F_A_mo;
        Eigen::MatrixXd F_gen = Eigen::MatrixXd::Zero(nb, nb);

        // Assemble the generalized Fock matrix for the non-redundant rotations:
        // inactive columns come from the total Fock matrix, while active columns
        // mix the inactive-driven term gamma * F_I with the explicit Q contraction.
        for (int p = 0; p < nb; ++p)
        {
            for (int i = 0; i < n_core; ++i)
                F_gen(p, i) = 2.0 * F_sum(p, i);
            for (int t = 0; t < n_act; ++t)
            {
                double value = 0.0;
                for (int u = 0; u < n_act; ++u)
                    value += gamma(t, u) * F_I_mo(p, n_core + u);
                value += Q(p, t);
                F_gen(p, n_core + t) = value;
            }
        }

        Eigen::MatrixXd g = 2.0 * (F_gen - F_gen.transpose());
        g.topLeftCorner(n_core, n_core).setZero();
        g.block(n_core, n_core, n_act, n_act).setZero();
        g.bottomRightCorner(n_virt, n_virt).setZero();

        // Symmetry-forbidden rotations are projected out explicitly so all later
        // optimizers can work on the full matrix layout without revisiting labels.
        if (use_sym && !mo_irreps.empty())
            for (int p = 0; p < nb; ++p)
                for (int q = 0; q < nb; ++q)
                {
                    if (p == q)
                        continue;
                    const int ip = (p < static_cast<int>(mo_irreps.size())) ? mo_irreps[p] : -1;
                    const int iq = (q < static_cast<int>(mo_irreps.size())) ? mo_irreps[q] : -1;
                    if (ip >= 0 && iq >= 0 && ip != iq)
                        g(p, q) = 0.0;
                }

        return g;
    }

    Eigen::MatrixXd fixed_ci_orbital_gradient(
        const Eigen::MatrixXd &C,
        const Eigen::MatrixXd &H_core,
        const std::vector<double> &eri,
        const Eigen::MatrixXd &gamma,
        const std::vector<double> &Gamma_vec,
        int n_core,
        int n_act,
        int n_virt,
        const std::vector<int> &mo_irreps,
        bool use_sym)
    {
        const int nbasis = static_cast<int>(C.rows());
        const Eigen::MatrixXd F_I_mo =
            build_inactive_fock_mo(C, H_core, eri, n_core, nbasis);
        const Eigen::MatrixXd F_A_mo =
            build_active_fock_mo(C, gamma, eri, n_core, n_act, nbasis);
        const ActiveIntegralCache active_integrals =
            build_active_integral_cache(eri, C, n_core, n_act, nbasis);
        const Eigen::MatrixXd Q = compute_Q_matrix(active_integrals, Gamma_vec);
        return compute_orbital_gradient(
            F_I_mo, F_A_mo, Q, gamma,
            n_core, n_act, n_virt, mo_irreps, use_sym);
    }

    Eigen::MatrixXd build_ci_orbital_gradient_correction(
        const Eigen::MatrixXd &Q1,
        int nbasis,
        int n_core,
        int n_act,
        int n_virt)
    {
        Eigen::MatrixXd G_CI = Eigen::MatrixXd::Zero(nbasis, nbasis);
        for (int p = 0; p < nbasis; ++p)
            for (int t = 0; t < n_act; ++t)
            {
                const int q = n_core + t;
                G_CI(p, q) += 2.0 * Q1(p, t);
                G_CI(q, p) -= 2.0 * Q1(p, t);
            }
        G_CI.topLeftCorner(n_core, n_core).setZero();
        G_CI.block(n_core, n_core, n_act, n_act).setZero();
        G_CI.bottomRightCorner(n_virt, n_virt).setZero();
        return G_CI;
    }

    double hess_diag(const Eigen::MatrixXd &F_sum, int p, int q)
    {
        return 2.0 * (F_sum(q, q) - F_sum(p, p));
    }

    Eigen::MatrixXd hessian_action(
        const Eigen::MatrixXd &R,
        const Eigen::MatrixXd &F_I_mo,
        const Eigen::MatrixXd &F_A_mo,
        int n_core,
        int n_act,
        int n_virt)
    {
        const int nb = n_core + n_act + n_virt;
        const Eigen::MatrixXd F_sum = F_I_mo + F_A_mo;
        Eigen::MatrixXd HR = Eigen::MatrixXd::Zero(nb, nb);
        auto cls = [&](int k)
        { return (k < n_core) ? 0 : (k < n_core + n_act) ? 1
                                                         : 2; };
        // The current orbital model keeps only the diagonal AH blocks, so the
        // Hessian action reduces to a per-pair energy denominator.
        for (int p = 0; p < nb; ++p)
            for (int q = 0; q < nb; ++q)
            {
                if (cls(p) == cls(q))
                    continue;
                HR(p, q) = hess_diag(F_sum, p, q) * R(p, q);
            }
        return HR;
    }

    Eigen::MatrixXd matrix_free_hessian_action(
        const Eigen::MatrixXd &R,
        const OrbitalHessianContext *context,
        const Eigen::MatrixXd &F_I_mo,
        const Eigen::MatrixXd &F_A_mo,
        int n_core,
        int n_act,
        int n_virt,
        const std::vector<int> &mo_irreps,
        bool use_sym)
    {
        if (context == nullptr ||
            context->C == nullptr ||
            context->S == nullptr ||
            context->H_core == nullptr ||
            context->eri == nullptr ||
            context->gamma == nullptr ||
            context->Gamma_vec == nullptr)
            return hessian_action(R, F_I_mo, F_A_mo, n_core, n_act, n_virt);

        const double max_elem = (R.size() > 0) ? R.cwiseAbs().maxCoeff() : 0.0;
        const double fd_step = std::max(context->fd_step, 1e-6);
        if (max_elem < 1e-14)
            return Eigen::MatrixXd::Zero(R.rows(), R.cols());

        const Eigen::MatrixXd C_plus =
            apply_orbital_rotation(*context->C, fd_step * R, *context->S);
        const Eigen::MatrixXd C_minus =
            apply_orbital_rotation(*context->C, -fd_step * R, *context->S);

        const Eigen::MatrixXd g_plus = fixed_ci_orbital_gradient(
            C_plus,
            *context->H_core,
            *context->eri,
            *context->gamma,
            *context->Gamma_vec,
            n_core,
            n_act,
            n_virt,
            mo_irreps,
            use_sym);
        const Eigen::MatrixXd g_minus = fixed_ci_orbital_gradient(
            C_minus,
            *context->H_core,
            *context->eri,
            *context->gamma,
            *context->Gamma_vec,
            n_core,
            n_act,
            n_virt,
            mo_irreps,
            use_sym);
        return (g_plus - g_minus) / (2.0 * fd_step);
    }

    Eigen::MatrixXd fep1_gradient_update(
        const Eigen::MatrixXd &G,
        const Eigen::MatrixXd &kappa,
        const Eigen::MatrixXd &F_I_mo,
        const Eigen::MatrixXd &F_A_mo,
        int n_core,
        int n_act,
        int n_virt)
    {
        const int nb = n_core + n_act + n_virt;
        const Eigen::MatrixXd F_sum = F_I_mo + F_A_mo;
        Eigen::MatrixXd updated = G;
        auto cls = [&](int k)
        { return (k < n_core) ? 0 : (k < n_core + n_act) ? 1
                                                         : 2; };
        // First-order estimate of how the orbital gradient changes under kappa when
        // we retain only the diagonal orbital Hessian.
        for (int p = 0; p < nb; ++p)
            for (int q = 0; q < nb; ++q)
            {
                if (cls(p) == cls(q) || std::abs(kappa(p, q)) < 1e-18)
                    continue;
                updated(p, q) += hess_diag(F_sum, p, q) * kappa(p, q);
            }
        return updated;
    }

    double quadratic_model_delta(
        const Eigen::VectorXd &g_flat,
        const Eigen::VectorXd &h_flat,
        const Eigen::VectorXd &x)
    {
        double delta = g_flat.dot(x);
        for (int k = 0; k < x.size(); ++k)
            delta += 0.5 * h_flat(k) * x(k) * x(k);
        return delta;
    }

    std::vector<RotPair> non_redundant_pairs(int n_core, int n_act, int n_virt)
    {
        const int nb = n_core + n_act + n_virt;
        std::vector<RotPair> pairs;
        pairs.reserve(n_core * n_act + n_core * n_virt + n_act * n_virt);
        auto cls = [&](int k)
        { return (k < n_core) ? 0 : (k < n_core + n_act) ? 1
                                                         : 2; };
        // Only inter-subspace rotations are variational parameters; rotations
        // within core, active, or virtual blocks are redundant gauge freedoms.
        for (int p = 0; p < nb; ++p)
            for (int q = p + 1; q < nb; ++q)
                if (cls(p) != cls(q))
                    pairs.push_back({p, q});
        return pairs;
    }

    Eigen::MatrixXd diagonal_preconditioned_orbital_step(
        const Eigen::MatrixXd &G,
        const Eigen::MatrixXd &F_I_mo,
        const Eigen::MatrixXd &F_A_mo,
        int n_core,
        int n_act,
        int n_virt,
        double level_shift,
        double max_rot,
        const std::vector<int> &mo_irreps,
        bool use_sym)
    {
        const int nb = n_core + n_act + n_virt;
        const Eigen::MatrixXd F_sum = F_I_mo + F_A_mo;
        Eigen::MatrixXd kappa = Eigen::MatrixXd::Zero(nb, nb);

        auto cls = [&](int k)
        { return (k < n_core) ? 0 : (k < n_core + n_act) ? 1
                                                         : 2; };

        for (int p = 0; p < nb; ++p)
            for (int q = p + 1; q < nb; ++q)
            {
                if (cls(p) == cls(q))
                    continue;
                if (use_sym && !mo_irreps.empty())
                {
                    const int ip = (p < static_cast<int>(mo_irreps.size())) ? mo_irreps[p] : -1;
                    const int iq = (q < static_cast<int>(mo_irreps.size())) ? mo_irreps[q] : -1;
                    if (ip >= 0 && iq >= 0 && ip != iq)
                        continue;
                }

                double denom = hess_diag(F_sum, p, q) + level_shift;
                if (std::abs(denom) < 1e-4)
                    denom = (denom >= 0.0) ? 1e-4 : -1e-4;

                const double step = -G(p, q) / denom;
                kappa(p, q) = step;
                kappa(q, p) = -step;
            }

        const double max_elem = kappa.cwiseAbs().maxCoeff();
        if (max_elem > max_rot)
            kappa *= max_rot / max_elem;
        return kappa;
    }

    CoupledStepDirection diagonal_preconditioned_coupled_step(
        const Eigen::MatrixXd &orbital_residual,
        const Eigen::VectorXd &ci_residual,
        const Eigen::VectorXd &c0,
        double E0,
        const Eigen::MatrixXd &F_I_mo,
        const Eigen::MatrixXd &F_A_mo,
        const Eigen::VectorXd &H_diag,
        int n_core,
        int n_act,
        int n_virt,
        double level_shift,
        double max_rot,
        const std::vector<int> &mo_irreps,
        bool use_sym,
        double response_precond_floor)
    {
        CoupledStepDirection step;
        step.orbital_step = diagonal_preconditioned_orbital_step(
            orbital_residual,
            F_I_mo,
            F_A_mo,
            n_core,
            n_act,
            n_virt,
            level_shift,
            max_rot,
            mo_irreps,
            use_sym);

        if (ci_residual.size() == 0 || H_diag.size() != ci_residual.size() || c0.size() != ci_residual.size())
        {
            step.ci_step = Eigen::VectorXd::Zero(ci_residual.size());
            return step;
        }

        double max_regularization = 0.0;
        step.ci_step = apply_response_diag_preconditioner(
            -ci_residual, H_diag, E0, response_precond_floor, max_regularization);
        step.ci_step = project_orthogonal(step.ci_step, c0);
        return step;
    }

    Eigen::MatrixXd augmented_hessian_step(
        const Eigen::MatrixXd &G,
        const Eigen::MatrixXd &F_I_mo,
        const Eigen::MatrixXd &F_A_mo,
        int n_core,
        int n_act,
        int n_virt,
        double level_shift,
        double max_rot,
        const std::vector<int> &mo_irreps,
        bool use_sym)
    {
        const int nb = n_core + n_act + n_virt;
        const Eigen::MatrixXd F_sum = F_I_mo + F_A_mo;
        const auto pairs = non_redundant_pairs(n_core, n_act, n_virt);
        const int npairs = static_cast<int>(pairs.size());
        if (npairs == 0)
            return Eigen::MatrixXd::Zero(nb, nb);

        Eigen::VectorXd g_flat(npairs);
        Eigen::VectorXd h_flat(npairs);
        Eigen::VectorXd D_flat(npairs);
        for (int k = 0; k < npairs; ++k)
        {
            const int p = pairs[k].p;
            const int q = pairs[k].q;
            if (use_sym && !mo_irreps.empty())
            {
                const int ip = (p < static_cast<int>(mo_irreps.size())) ? mo_irreps[p] : -1;
                const int iq = (q < static_cast<int>(mo_irreps.size())) ? mo_irreps[q] : -1;
                if (ip >= 0 && iq >= 0 && ip != iq)
                {
                    g_flat(k) = 0.0;
                    h_flat(k) = 1.0;
                    D_flat(k) = 1.0;
                    continue;
                }
            }
            g_flat(k) = G(p, q);
            h_flat(k) = hess_diag(F_sum, p, q);
            D_flat(k) = h_flat(k) + level_shift;
            if (std::abs(D_flat(k)) < 1e-4)
                D_flat(k) = (D_flat(k) >= 0.0) ? 1e-4 : -1e-4;
        }

        auto cap_step = [&](Eigen::VectorXd x)
        {
            if (!x.allFinite())
                return x;
            const double max_x = x.cwiseAbs().maxCoeff();
            if (max_x > max_rot)
                x *= max_rot / max_x;
            return x;
        };

        auto damped_newton = [&](double lm_shift)
        {
            Eigen::VectorXd x(npairs);
            for (int k = 0; k < npairs; ++k)
            {
                double denom = h_flat(k) + lm_shift;
                if (std::abs(denom) < 1e-18)
                    denom = (denom >= 0.0) ? 1e-18 : -1e-18;
                x(k) = -g_flat(k) / denom;
            }
            return x;
        };

        const double D_min = D_flat.minCoeff();
        double eps_lo = D_min - 1.0 - g_flat.norm();
        double eps_hi = D_min - 1e-8;
        auto f = [&](double e)
        {
            double s = 0.0;
            for (int k = 0; k < npairs; ++k)
            {
                const double d = D_flat(k) - e;
                s += (g_flat(k) / d) * (g_flat(k) / d);
            }
            return s - 1.0;
        };

        double eps_star = 0.0;
        // Solve the diagonal augmented-Hessian secular equation in the scalar
        // shift eps so we can compare AH and damped-Newton candidates cheaply.
        if (f(eps_lo) * f(eps_hi) <= 0.0)
            for (int bi = 0; bi < 50; ++bi)
            {
                eps_star = 0.5 * (eps_lo + eps_hi);
                if (f(eps_lo) * f(eps_star) <= 0.0)
                    eps_hi = eps_star;
                else
                    eps_lo = eps_star;
                if (eps_hi - eps_lo < 1e-12)
                    break;
            }

        Eigen::VectorXd x_ah(npairs);
        for (int k = 0; k < npairs; ++k)
            x_ah(k) = -g_flat(k) / (D_flat(k) - eps_star);

        struct Candidate
        {
            Eigen::VectorXd x;
            double score = std::numeric_limits<double>::infinity();
        };

        Candidate best;
        auto consider = [&](Eigen::VectorXd x)
        {
            x = cap_step(std::move(x));
            if (!x.allFinite())
                return;
            // Score candidates by the diagonal quadratic model and prefer the
            // larger step only when two candidates are effectively degenerate.
            const double score = quadratic_model_delta(g_flat, h_flat, x);
            if (score < best.score - 1e-12 || (std::abs(score - best.score) <= 1e-12 && x.norm() > best.x.norm() + 1e-12))
            {
                best.x = std::move(x);
                best.score = score;
            }
        };

        for (double lm_scale : {0.0, 0.25, 1.0, 4.0, 16.0})
            consider(damped_newton(lm_scale * std::max(level_shift, 1e-6)));
        consider(x_ah);

        Eigen::VectorXd x = best.x;
        if (!x.allFinite() || x.cwiseAbs().maxCoeff() < 1e-14)
            x = cap_step(damped_newton(std::max(level_shift, 1e-6)));

        Eigen::MatrixXd kappa = Eigen::MatrixXd::Zero(nb, nb);
        for (int k = 0; k < npairs; ++k)
        {
            const int p = pairs[k].p;
            const int q = pairs[k].q;
            kappa(p, q) = x(k);
            kappa(q, p) = -x(k);
        }

        const double max_k = kappa.cwiseAbs().maxCoeff();
        if (max_k > max_rot)
            kappa *= max_rot / max_k;
        return kappa;
    }

    Eigen::MatrixXd apply_orbital_rotation(
        const Eigen::MatrixXd &C_old,
        const Eigen::MatrixXd &kappa,
        const Eigen::MatrixXd &S)
    {
        const int nb = static_cast<int>(C_old.rows());
        const Eigen::MatrixXd I = Eigen::MatrixXd::Identity(nb, nb);
        // Apply the antisymmetric orbital step with a Cayley transform, then
        // restore S-orthonormality with a symmetric Löwdin-like cleanup.
        Eigen::MatrixXd C_new =
            C_old * (I - 0.5 * kappa).colPivHouseholderQr().solve(I + 0.5 * kappa);

        Eigen::MatrixXd ovlp = C_new.transpose() * S * C_new;
        Eigen::SelfAdjointEigenSolver<Eigen::MatrixXd> eig(ovlp);
        Eigen::VectorXd inv_sqrt = eig.eigenvalues().array().max(1e-12).sqrt().inverse();
        return C_new * (eig.eigenvectors() * inv_sqrt.asDiagonal() * eig.eigenvectors().transpose());
    }

} // namespace HartreeFock::Correlation::CASSCF
