#!/usr/bin/env python3
"""
vault_to_claude.py — Aggregates Obsidian vault notes into CLAUDE.md

Usage:
    python3 scripts/vault_to_claude.py [--vault VAULT_DIR] [--output OUTPUT_FILE] [--force]

Only notes with `include_in_claude: true` in their YAML frontmatter are included.
Notes are ordered by type (architecture → implementation → gotcha → status)
then by priority (critical → high → medium → low).

Run automatically via Claude Code PostToolUse hook when vault files change.
"""

import os
import re
import sys
import argparse
from pathlib import Path
from typing import Optional

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

REPO_ROOT = Path(__file__).parent.parent
VAULT_DIR = REPO_ROOT / "vault"
OUTPUT_FILE = REPO_ROOT / "CLAUDE.md"

TYPE_ORDER = {"architecture": 0, "implementation": 1, "gotcha": 2, "status": 3, "reference": 4}
PRIORITY_ORDER = {"critical": 0, "high": 1, "medium": 2, "low": 3}

# ---------------------------------------------------------------------------
# Frontmatter parsing
# ---------------------------------------------------------------------------

FRONTMATTER_RE = re.compile(r"^---\s*\n(.*?)\n---\s*\n", re.DOTALL)
WIKILINK_RE = re.compile(r"\[\[([^\]|]+)(?:\|[^\]]+)?\]\]")


def parse_frontmatter(text: str) -> tuple[dict, str]:
    """Return (metadata_dict, body_text). Returns ({}, text) if no frontmatter."""
    m = FRONTMATTER_RE.match(text)
    if not m:
        return {}, text
    raw = m.group(1)
    body = text[m.end():]
    meta: dict = {}
    for line in raw.splitlines():
        if ":" in line:
            key, _, val = line.partition(":")
            key = key.strip()
            val = val.strip()
            # Parse booleans
            if val.lower() == "true":
                meta[key] = True
            elif val.lower() == "false":
                meta[key] = False
            # Parse lists like [a, b, c]
            elif val.startswith("[") and val.endswith("]"):
                meta[key] = [v.strip() for v in val[1:-1].split(",")]
            else:
                meta[key] = val
    return meta, body


def strip_obsidian(text: str) -> str:
    """Convert Obsidian-specific syntax to plain Markdown."""
    # [[Note Name]] → Note Name
    text = WIKILINK_RE.sub(r"\1", text)
    return text


# ---------------------------------------------------------------------------
# Note collection
# ---------------------------------------------------------------------------

def collect_notes(vault_dir: Path) -> list[dict]:
    notes = []
    for md_file in sorted(vault_dir.rglob("*.md")):
        # Skip .obsidian config files
        if ".obsidian" in md_file.parts:
            continue
        # Skip the index note (it's navigation, not content)
        if md_file.name.startswith("00 -"):
            continue

        raw = md_file.read_text(encoding="utf-8")
        meta, body = parse_frontmatter(raw)

        if not meta.get("include_in_claude", False):
            continue

        notes.append({
            "file": md_file,
            "name": meta.get("name", md_file.stem),
            "type": meta.get("type", "reference"),
            "priority": meta.get("priority", "medium"),
            "body": strip_obsidian(body.strip()),
        })

    # Sort: by type order, then priority order, then name
    notes.sort(key=lambda n: (
        TYPE_ORDER.get(n["type"], 99),
        PRIORITY_ORDER.get(n["priority"], 99),
        n["name"],
    ))
    return notes


# ---------------------------------------------------------------------------
# CLAUDE.md generation
# ---------------------------------------------------------------------------

SECTION_HEADERS = {
    "architecture": "## Architecture",
    "implementation": "## Implementation",
    "gotcha": "## Gotchas & Pitfalls",
    "status": "## Status",
    "reference": "## References",
}


def generate_claude_md(notes: list[dict]) -> str:
    lines = [
        "<!-- AUTO-GENERATED by scripts/vault_to_claude.py — edit vault notes, not this file -->",
        "",
        "# Planck — Claude Code Context",
        "",
        "> This file is generated from the Obsidian vault in `vault/`. "
        "To update it, edit the relevant vault note and the hook will regenerate this file.",
        "",
    ]

    current_type: Optional[str] = None
    for note in notes:
        note_type = note["type"]
        if note_type != current_type:
            current_type = note_type
            header = SECTION_HEADERS.get(note_type, f"## {note_type.title()}")
            lines.append("")
            lines.append("---")
            lines.append("")
            lines.append(header)
            lines.append("")

        lines.append(note["body"])
        lines.append("")

    lines.append("")
    lines.append("---")
    lines.append("*Generated from vault notes. Source of truth: `vault/`.*")
    lines.append("")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Staleness check
# ---------------------------------------------------------------------------

def vault_is_newer_than_output(vault_dir: Path, output_file: Path) -> bool:
    """Return True if any vault note is newer than the output file."""
    if not output_file.exists():
        return True
    output_mtime = output_file.stat().st_mtime
    for md_file in vault_dir.rglob("*.md"):
        if ".obsidian" in md_file.parts:
            continue
        if md_file.stat().st_mtime > output_mtime:
            return True
    return False


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--vault", type=Path, default=VAULT_DIR,
                        help="Path to Obsidian vault directory")
    parser.add_argument("--output", type=Path, default=OUTPUT_FILE,
                        help="Output CLAUDE.md path")
    parser.add_argument("--force", action="store_true",
                        help="Regenerate even if vault has not changed")
    parser.add_argument("--quiet", action="store_true",
                        help="Suppress informational output")
    args = parser.parse_args()

    vault_dir: Path = args.vault
    output_file: Path = args.output

    if not vault_dir.exists():
        print(f"[vault_to_claude] ERROR: vault dir not found: {vault_dir}", file=sys.stderr)
        return 1

    if not args.force and not vault_is_newer_than_output(vault_dir, output_file):
        if not args.quiet:
            print(f"[vault_to_claude] CLAUDE.md is up to date, skipping.")
        return 0

    notes = collect_notes(vault_dir)
    if not notes:
        print("[vault_to_claude] WARNING: no notes with include_in_claude: true found.", file=sys.stderr)
        return 0

    content = generate_claude_md(notes)
    output_file.write_text(content, encoding="utf-8")

    if not args.quiet:
        print(f"[vault_to_claude] Generated {output_file} from {len(notes)} vault notes.")

    return 0


if __name__ == "__main__":
    sys.exit(main())
