name: Mirror to GitLab

on:
  push:
    branches:
      - main
      - devel

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Start ssh-agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.GITLAB_SSH_KEY }}

      - name: Add GitLab host key
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan gitlab.com >> ~/.ssh/known_hosts

      - name: Push mirror to GitLab
        run: |
          git remote add gitlab git@gitlab.com:hemanth_hari/planck-refactored.git
          git push gitlab --all
          git push gitlab --tags
